// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------ //
// screen //
// ------ //

#define screen_wrap_target 0
#define screen_wrap 8
#define screen_pio_version 0

static const uint16_t screen_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block
    0x6064, //  1: out    null, 4
    0xe02b, //  2: set    x, 11
    0x7001, //  3: out    pins, 1         side 0
    0x1843, //  4: jmp    x--, 3          side 1
    0x6064, //  5: out    null, 4
    0xe02b, //  6: set    x, 11
    0x7001, //  7: out    pins, 1         side 0
    0x1847, //  8: jmp    x--, 7          side 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program screen_program = {
    .instructions = screen_program_instructions,
    .length = 9,
    .origin = -1,
    .pio_version = screen_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config screen_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + screen_wrap_target, offset + screen_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

